apiVersion: rbac.authorization.k8s.io
kind: ClusterRoleBinding
metadata:
  name: tajcluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: Admins
