apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: group-sync-operator
resources:
- namespace.yaml
- subscription.yaml
- operatorgroup.yaml
- groupsync.yaml
secretGenerator:
- name: group-sync-app-secret
  namespace: group-sync-operator
  literals:
  - appId=
  files:
  - privateKey=

generatorOptions:
  disableNameSuffixHash: true
