apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - machineconfig.yaml
  - namespace.yaml
  - securitycontextconstraints.yaml
  - storageclass.yaml
