apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployments/
- persistentVolumeClaim/
- services/
- ingress/
secretGenerator:
- name: mariadb-secret
  literals:
  - dbuser=tsalawu
  - dbpassword=testing
  - dbname=testdb
  - dbrootpassword=testing
