apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - OAuth.yaml
  - group-sync-operator/

secretGenerator:
- name: taj-org-secret
  namespace: openshift-config
  files:
  - clientSecret=git-org-secret.txt

generatorOptions:
  disableNameSuffixHash: true
