---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: github
      mappingMethod: claim
      type: GitHub
      github:
        clientID: 
        clientSecret:
          name: 
        teams:
          - GitHubIDPTest/Admins
          - GitHubIDPTest/Viewers

