---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: github
      mappingMethod: claim
      type: GitHub
      github:
        clientID: 6b5aae649836181457ea
        clientSecret:
          name: taj-org-secret
        teams:
          - GitHubIDPTest/Admins
          - GitHubIDPTest/Member

